import './style.css';

type Card={s:string,r:string,id:string}; type Player={name:string,score:number,hand:Card[]};
type State={game:string,winning:number,players:Player[],current:number,nodes:(Card|null)[],deckCount:number,usedCount:number,round:number,over:boolean,winner:number|null,log:string[]};
const app=document.querySelector<HTMLDivElement>('#app')!; let ws:WebSocket|null=null; let room=''; let me=-1; let S:State|null=null; let selected:number[]=[]; let node:number|null=null;
const suits=['♠','♥','♦','♣'], ranks=['2','3','4','5','6','7','8','9','10','J','Q','K','A']; const values=Object.fromEntries(ranks.map((r,i)=>[r,i+2]));
const points:any={'Two Pair':5,'Three of a Kind':10,'Straight':15,'Flush':20,'Full House':25,'Four of a Kind':50,'Straight Flush':75,'Royal Flush':100};
function lobby(msg=''){app.innerHTML=`<div class="app"><div class="top"><div><h1>Node Attack</h1><div class="sub">Online poker-node strategy • room based multiplayer</div></div></div><div class="panel setup"><div class="field"><label>Game</label><select disabled><option>Node Attack</option></select></div><div class="field"><label>Multiplayer</label><select disabled><option>Online Multiplayer</option></select></div><div class="field"><label>Winning score</label><input id="win" type="number" min="1" step="0.5" value="150"></div></div><div class="panel online"><h2>Play online</h2><p class="sub">Create a room and send the code to another player, or join an existing room.</p><div class="row"><button id="create" class="primary">Create Room</button><input id="code" maxlength="6" placeholder="ROOM CODE"><button id="join">Join Room</button></div><div class="message">${msg}</div></div></div>`; document.querySelector('#create')!.addEventListener('click',()=>connect('create')); document.querySelector('#join')!.addEventListener('click',()=>connect('join',(document.querySelector('#code') as HTMLInputElement).value.trim().toUpperCase()));}
function connect(type:'create'|'join',code=''){const proto=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${proto}://${location.host}`);ws.onopen=()=>ws!.send(JSON.stringify({type,room:code,winning:+(document.querySelector('#win') as HTMLInputElement)?.value||150}));ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='welcome'){room=m.room;me=m.player;S=m.state;selected=[];node=null;render()}else if(m.type==='state'){S=m.state;selected=[];node=null;render()}else if(m.type==='error'){lobby(m.message)}};ws.onclose=()=>{if(S)lobby('Disconnected from the server.');S=null;me=-1;}};
function send(action:any){ws?.send(JSON.stringify({type:'action',room,action}));}
function card(c:Card|null,hide=false){if(!c)return ''; if(hide)return '<div class="card back">?</div>'; return `<div class="card ${c.s==='♥'||c.s==='♦'?'red':''}"><div class="rank">${c.r}</div><div class="suit">${c.s}</div></div>`}
function render(){if(!S)return lobby(); const p=S.players[me]; const human=S.current===me&&!S.over; app.innerHTML=`<div class="app"><div class="top"><div><h1>Node Attack</h1><div class="sub">Room <b>${room}</b> • You are Player ${me+1}</div></div><button id="leave" class="danger">Leave</button></div><div class="scorebar panel">${S.players.map((x,i)=>`<div class="score ${i===S.current?'active':''}"><strong>Player ${i+1}${i===me?' (You)':''}</strong><br>${x.score} / ${S.winning}</div>`).join('')}</div><div class="panel"><div class="turn">${S.over?`🏆 Player ${S.winner!+1} wins!`:S.current===me?`Your turn • Round ${S.round}`:`Player ${S.current+1}'s turn • waiting…`}</div><div class="board"><div class="pile">DRAW<br>PILE<br><b>${S.deckCount}</b></div><div class="nodes">${S.nodes.map((c,i)=>`<div class="node ${node===i?'selected':''}" data-node="${i}">${card(c)}</div>`).join('')}</div><div class="pile">USED<br>PILE<br><b>${S.usedCount}</b></div></div></div><div class="panel"><div class="handtitle"><b>Your hand</b><span class="sub">${selected.length} selected${node!==null?' • node '+(node+1):''}</span></div><div class="hand">${p.hand.map((c,i)=>`<div data-card="${i}" class="handcard ${selected.includes(i)?'selected':''}">${card(c)}</div>`).join('')}</div><div class="controls"><button id="play" class="primary" ${!human||node===null||!selected.length?'disabled':''}>Play Selected</button><button id="discard" class="danger" ${!human||!selected.length?'disabled':''}>Discard Selected</button><button id="finish" ${!human?'disabled':''}>Finish Turn</button><button id="clear">Clear Selection</button></div></div><div class="panel"><b>Game Log</b><div class="log">${S.log.map(x=>`<div>• ${x}</div>`).join('')}</div></div>${S.over?'<div class="panel center"><button id="rematch" class="success">Rematch</button></div>':''}</div>`;
 document.querySelector('#leave')!.addEventListener('click',()=>{ws?.close();lobby()}); document.querySelectorAll<HTMLElement>('[data-node]').forEach(e=>e.onclick=()=>{const i=+e.dataset.node!; if(human&&S && S.nodes[i]){node=node===i?null:i;render()}}); document.querySelectorAll<HTMLElement>('[data-card]').forEach(e=>e.onclick=()=>{const i=+e.dataset.card!;if(human&&S){selected=selected.includes(i)?selected.filter(x=>x!==i):selected.length<4?[...selected,i]:selected;render()}}); document.querySelector('#play')!.addEventListener('click',()=>send({kind:'play',node,indices:selected})); document.querySelector('#discard')!.addEventListener('click',()=>send({kind:'discard',indices:selected})); document.querySelector('#finish')!.addEventListener('click',()=>send({kind:'finish'})); document.querySelector('#clear')!.addEventListener('click',()=>{selected=[];node=null;render()}); document.querySelector('#rematch')?.addEventListener('click',()=>send({kind:'rematch'}));}
lobby();
